### ISSUE TITLE
Prolific Pooka Population

### ISSUE THREAD

**Issue by Drakoflame** [SnappyDragon18/Bloom-and-Gloom#10]
I'm built next to a river in a dark oak biome, and there was a fairy circle near by that I pulled up because I love the little fairy lights. I was building around my base, and started to notice some intense lag, when I glanced up at my minimap and saw a _**LOT**_ of hostile mobs. I went to investigate and found a LOT of pookas just hopping about minding their own. There doesn't seem to be a spawn cap for them, and more and more keep generating and it causes issues cus, well there's a LOT of them. Even after kiling them and heading back home, I looked back at my minimap and saw that there were already a bunch more.

![image](https://user-images.githubusercontent.com/8823913/148215589-6991ea9b-8c0d-4164-8bf9-ae1c61202fbb.png)

I'm not sure what else to include with this issue post, I just thought it'd be worth mentioning just in case.
Using Habitat 1.1.1 for 1.18.1
Forge 39.0.8
(and a lot of other mods)

**Comment by SnappyDragon64** [comment]
Pooka do use the hostile mob cap but this is likely happening since they can spawn during the day and spawn until the mob cap is entirely filled by them.

I'll make them only spawn at night and maybe tie their spawning to moon phases in 1.1.2 along with some other changes.

**Comment by SnappyDragon64** [comment]
For now, replacing the grass blocks in the vicinity of the fairy ring with anything should prevent them from spawning.

**Comment by Drakoflame** [comment]
Good to know thanks! I'll be sure to replace the blocks to prevent them until the fix is rolled out!

(Should I mark this as closed or wait for the fix?)

**Comment by SnappyDragon64** [comment]
I'll close it after fixing the issue. Also, IIRC the bounding box of the ring expands 2 blocks outwards from the ring so the area where they can spawn is 15x15, centred on the ring.

Thanks for reporting.

**Comment by SnappyDragon64** [comment]
[Should be fine now](https://github.com/SnappyDragon18/Habitat/commit/fa9007d4a72e073d3219556edaab42bd83ada19a)
