### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alexrsosa97** [SnappyDragon18/Bloom-and-Gloom#13]
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag mod.schnappdragon.habitat.common.block.entity.RafflesiaBlockEntity.save(net.minecraft.nbt.CompoundTag)
[crash-2022-01-21_20.51.35-server.txt](https://github.com/SnappyDragon18/Habitat/files/7917425/crash-2022-01-21_20.51.35-server.txt)
'

**Comment by SnappyDragon64** [comment]
[Fixed](https://github.com/SnappyDragon18/Habitat/commit/3e1dc5f4a4ee210120489f78a9df072175c6901e)
