### ISSUE TITLE
Visual bug with Magnesium (Forge version of Sodium)

### ISSUE THREAD

**Issue by Finelarme9** [SnappyDragon18/Bloom-and-Gloom#14]
Hello.

Visual bug with [Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) (Forge version of Sodium) of "slime fern" and "kabloom pulp". I have tried to change the json but nothing changed. If it is not possible to solve this, how can I avoid those plants to spawn naturally please ? Changing Magnesium settings doesn't solve this.

https://i.ibb.co/d500Nq9/2022-01-29-15-11-49.png

**FILES USED**
1.18.1-forge-39.0.63
habitat-1.1.2.jar
magnesium-0.4.0-alpha6.jar

**Comment by SnappyDragon64** [comment]
There is no config to disable plant spawning at the moment. I think it would be better to report this to Magnesium.

**Comment by Finelarme9** [comment]
Ok, thank you! There is this kind of problem for many other mods (list below), so I will ask to Magnesium author.

- Biome-Makeover (visual bug)
- Brassgeodes (visual bug)
- Macaws-bridges (visual bug)
- Chisels bits (doesn't show blocks)
- Chalk (doesn't show marks)
- Snow-real-magic (doesn't show snow)
