### ISSUE TITLE
Lag spikes on server due to AI updates?

### ISSUE THREAD

**Issue by SeriousCreeper** [SnappyDragon18/Bloom-and-Gloom#2]
Heya,

we were using this mod on our server using the Seriously Thirsty modpack (https://www.curseforge.com/minecraft/modpacks/seriously-thirsty). 
Unfortunately we noticed a lot of lag spikes and rubber banding while exploring (already generated chunks), especially areas that had a few rafflesia in it. 

Looking at the thread using Spark, and unless im misreading this, it seems like the AvoidRafflesiaGoal method is taking up a lot of time, for example this is for 1 animal: 
![chrome_2021-01-11_08-53-48](https://user-images.githubusercontent.com/571759/104213207-e5ee8980-53ea-11eb-9aaf-371675f6720b.png) 
and this gets called for several animals, causing the entire update to be almost 8000ms long. 

Here is the full report: https://spark.lucko.me/#JOopofHzEF

We were using version 0.2 and forge 35.1.28. 
There are also several other mods so i dunno if it could be a combination of things. 

Let me know if you need any other info! 

Cheers,
SC

**Comment by SnappyDragon64** [comment]
Resolved
