### ISSUE TITLE
Client/Server desync with a lot of Habitat stuff.

### ISSUE THREAD

**Issue by belathus** [SnappyDragon18/Bloom-and-Gloom#22]
Fairy ring doors and trapdoors, when opened by other players or villagers, don't send an update to the other clients. IE: if I open a door on the server, the other players will see it as closed.

Something that happens that is much more apparent is using bone meal to grow fairy ring mushrooms. The mushrooms become a stem, letting me know a mushroom has grown, but the entire rest of the giant mushroom is invisible. The white outline in the second screenshot is me holding the FTB Ultimine hotkey showing the rest of the stem blocks in the giant mushroom. The only way I've been able to see the rest of the tree is by re-logging onto the server or leaving the area entirely and coming back.

![2022-08-17_17 20 03](https://user-images.githubusercontent.com/3826783/185246065-48c49af2-b8cf-48cf-952e-642901e13995.png)
![2022-08-17_17 20 36](https://user-images.githubusercontent.com/3826783/185246143-82371b1b-5f5e-4579-a7af-581a29f43cf4.png)

**Comment by SnappyDragon64** [comment]
Thank you for reporting, I will look into it soon.

**Comment by SnappyDragon64** [comment]
I have looked into this and fairy ring doors and trapdoors use the vanilla Door and Trapdoor classes, so they should function the same.

The mushroom growing code also sets blocks the same way as it is done for vanilla mushroom growing so I'm not sure what might be causing this.
