### ISSUE TITLE
[1.19.2] No worldgen features are being generated & no mobs are spawning.

### ISSUE THREAD

**Issue by Bobisnotap** [SnappyDragon18/Bloom-and-Gloom#26]
Hey, I've been playing the 1.19.2 version of habitat for a bit, and I've noticed that non of the worldgen features (fairy ring mushrooms, ball cacti, rafflesias, kabloom bushes, slime ferns) have been appearing at all. Same deal with both mobs, though it's to be expected that pookas wouldn't appear without the fairy rings. I haven't found anything in the logs that would help diagnose what's going wrong but I think it's either 1.19 worldgen changes or possibly a conflict w blueprint or terrablender.
I've still been able to see some of the content though in survival thanks to wandering traders! So at least that works.

**Comment by SnappyDragon64** [comment]
The 1.19.2 alpha does not have worldgen or spawns. A release version with worldgen and mob spawns should be out by the end of this weekend.

**Comment by Bobisnotap** [comment]
Ah! Alright, good to know. I'll close this, thank you for the clarification.
