### ISSUE TITLE
Breaking kabloom fruit pile with silk touch pickaxe does not cost durability

### ISSUE THREAD

**Issue by thelegitdolt** [SnappyDragon18/Bloom-and-Gloom#27]

**Comment by thelegitdolt** [comment]
unplayable

**Comment by SnappyDragon64** [comment]
Thanks for the report, will be fixed soon.

**Comment by thelegitdolt** [comment]
thank you . hope you don't mind the super minor bugs that does nothing

**Comment by SnappyDragon64** [comment]
Seems to be because it breaks instantly. Might give the block some hardness or keep it the way it is.
