### ISSUE TITLE
Axes disabled in 1.2.0

### ISSUE THREAD

**Issue by Kelpiesaurus** [SnappyDragon18/Bloom-and-Gloom#28]
I updated to the latest version, and it has disabled axes, meaning axes no longer break anything faster than doing it barehanded. And when I found a fairy ring and tried to harvest the mushrooms, barehanded and with shears, they were just destroyed when I broke them and didn't drop anything. I went back to Habitat 1.1.9, and axes work again and I can collect the fairy ring mushrooms. The mod Jade shows me that axes are the preferred tool for breaking the fairy ring mushrooms, so I assume it's part of the same issue. With Habitat updated to 1.2.0, Jade does not show the axe as the preferred tool for any block.

**Comment by SnappyDragon64** [comment]
I'll look into it.
