### ISSUE TITLE
Missing Ball Cactus recipe?

### ISSUE THREAD

**Issue by ArkVeil** [SnappyDragon18/Bloom-and-Gloom#30]
Are the flowering huge ball cactus blocks supposed to craft into the smaller variants? I noticed the cactus balls all having an "empty tag" for the crafting recipe.

![image](https://github.com/SnappyDragon64/Habitat/assets/40077783/c2f81d71-e392-4ddb-8d73-4365654f5670)

**Comment by SnappyDragon64** [comment]
It used to be a thing but was supposed to be removed. It seems that I forgot to remove the recipe JSONs.
