### ISSUE TITLE
[1.20.1] No worldgen features are being generated & no mobs are spawning.

### ISSUE THREAD

**Issue by moninformateur** [SnappyDragon18/Bloom-and-Gloom#31]
Is this expected? I can't find any passerine in any forest, no flowers either.

**Comment by SnappyDragon64** [comment]
I'll look into it and release a fix soon.

**Comment by SnappyDragon64** [comment]
I just tested this and everything seems to be working. It might just be a spawn rate thing?

**Comment by moninformateur** [comment]
The flowers do seem to spawn so that was my mistake. I just rechecked and it seems the culprit was the SpawnBalanceUtilities in the modpack made Passerine to be low in spawn. Sorry for bothering and thank you for testing!
