### ISSUE TITLE
[CRASH] [FORGE 1.20.1] Habitat and EveryCompat Cause Crash

### ISSUE THREAD

**Issue by Camawama** [SnappyDragon18/Bloom-and-Gloom#33]
FORGE VERSION: 1.20.1-47.2.1
HABITAT VERSION: 1.2.5
EVERY COMPAT VERSION: 1.20-2.6.12

When I have both of these mods enabled, I get a crash.

LOGS:
[latest.log](https://github.com/SnappyDragon64/Habitat/files/13171949/latest.log)

CRASH REPORT:
[crash-2023-10-25_19.53.35-client.txt](https://github.com/SnappyDragon64/Habitat/files/13171952/crash-2023-10-25_19.53.35-client.txt)

**Comment by SnappyDragon64** [comment]
Seems to be on EveryCompat's side
It's adding a cabinet for fairy ring woodset when there already is one

**Comment by Camawama** [comment]
https://github.com/MehVahdJukaar/WoodGood/issues/298

**Comment by Camawama** [comment]
> Seems to be on EveryCompat's side It's adding a cabinet for fairy ring woodset when there already is one

Oh interesting, I see that now. I wonder how Every Compat checks for that kind of stuff :\

**Comment by Xelbayria** [comment]
<strike>Does **HABITAT** have supported mod? or addon that allow to support **Habitat** with other mods like **Biomes O' Plenty**</strike>

does **Habitat** have any foreign wood Blocks? According to the latest.log, it was registering Wood Blocks, then errors. 

---
EDIT: 
I am gathering information to find out what's going on.

**Comment by Xelbayria** [comment]
ok i've finished gathering information. I've ran test on this issue. With the latest version of Every Compat & Moonlight's latest version with Habitat, I had no issue.  I noticed the problem was not in EveryCompat, but was in Moonlight according to `latest.log`. Apparently, it was on @Camawama's issue.  His version of Moonlight was outdated.

**Comment by ambientNexus** [comment]
> ok i've finished gathering information. I've ran test on this issue. With the latest version of Every Compat & Moonlight's latest version with Habitat, I had no issue. I noticed the problem was not in EveryCompat, but was in Moonlight according to `latest.log`. Apparently, it was on @Camawama's issue. His version of Moonlight was outdated.

Using the latest versions of Moonlight, Every Compat, and Habitat, a crashing issue still seems to occur. However, this time it appears as if it results from a strange bug between MrCrayfish's furniture mod and Farmers' Delight, as it encounters an error with something to do with a "cabinet" block id.

**Comment by Xelbayria** [comment]
The details are in [EveryCompat](MehVahdJukaar/WoodGood#298)'s last post - There are conflicts between 3 mods. It doesn't matter which mods add foreign woods (habitats or Biomes O' Plenty).

**Comment by SnappyDragon64** [comment]
https://github.com/MehVahdJukaar/WoodGood/issues/298

**Comment by SnappyDragon64** [comment]
@Xelbayria Would it be correct to say that the issue is on EveryCompat's side and not Habitat's?

**Comment by Xelbayria** [comment]
> @Xelbayria Would it be correct to say that the issue is on EveryCompat's side and not Habitat's?

unlikely. In my last post via the link (EveryCompat's last post), I mentioned this 👇 
> ran another test using Biomes O' Plenty without Habitat. The result is no issues. 

so I ran the test with **Habitat**, there are issues. I don't think it's **EveryCompat**'s side or **Habitat**'s side. Something else is causing this. I wasn't able to find out what's the cause, so it's unknown.

**Comment by SnappyDragon64** [comment]
Does EveryCompat register a set of blocks for each registered WoodType? Any way to prevent it if so? Seems like BOP has no issues because it doesn't add cabinets for its WoodTypes.

**Comment by Xelbayria** [comment]
> Seems like BOP has no issues because it doesn't add cabinets for its WoodTypes.

actually, it added Cabinets for its woodtypes. I've checked. 

> Does EveryCompat register a set of blocks for each registered WoodType? Any way to prevent it if so?

Yes, it does. Well. take a look at `everycomp-common.toml` in config.   it has a list of wood types and types of furniture that you could disable. I've tried it to fix the problem, but it doesn't work. The furniture with `false` are still being registered. 
my best guess is Moonlight may have to do with the problem. this is not confirmed.

**Comment by SnappyDragon64** [comment]
> actually, it added Cabinets for its woodtypes. I've checked. 

My bad, I worded that weirdly. I meant that BOP Itself does not add cabinets.

> The furniture with false are still being registered.

I see.

**Comment by Xelbayria** [comment]
> My bad, I worded that weirdly. I meant that BOP Itself does not add cabinets.

???  Okay, here's a few questions: 
1) do you mean BOP has cabinets but doesn't add them? 
As far as I know, BOP doesn't have cabinets, other mods do. Like **Macaw's Furniture**

2) do you mean EC doesn't combine cabinets with BOP's wood types? 

3) does `everycomp-common.toml` has this: `cabinet = false`. If yes, then try to set it to `true`, so the cabinet will be added with other wood types.  Note; they should be set to `true` by default.

**Comment by SnappyDragon64** [comment]
That BOP does not have cabinets.

**Comment by Xelbayria** [comment]
> That BOP does not have cabinets.

That clears up the confusion. Are there any questions you have for me?

**Comment by SnappyDragon64** [comment]
> That clears up the confusion. Are there any questions you have for me?

Nope, thanks
