### ISSUE TITLE
Flower Pots give nothing when right-clicked

### ISSUE THREAD

**Issue by WenXin20** [SnappyDragon18/Bloom-and-Gloom#36]
```
Minecraft v1.20.1
Habitat v1.3.1
```

When most potted flowers are right-clicked, no item is returned to the player. The potted blowball also has a missing model.

![image](https://github.com/SnappyDragon64/Habitat/assets/12000593/6fc5b4d5-4daa-421b-a795-0dc035edfa0d)

**Comment by SnappyDragon64** [comment]
Will fix next week
