### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [SnappyDragon18/Bloom-and-Gloom#7]
`Minecraft 1.16.5`
`Forge v36.1.24`
`Habitat v0.3a2`

My server crashed after updating from Bloom and Gloom to Habitat.
[Crash Report](https://gist.github.com/WenXin20/400d92e9ab73d3dbd9ff62741f0af406)

**Comment by SnappyDragon64** [comment]
That's odd, crash log mentions a missing vanilla file. Does it persist after trying again?

**Comment by WenXin20** [comment]
Hmm, not sure. I'll have to try again in a bit.

**Comment by WenXin20** [comment]
It still crashes. Isn't it crashing because it tries to load a client-side method on the server?

**Comment by SnappyDragon64** [comment]
I'll fix it and change the file uploaded on curseforge soon.

**Comment by WenXin20** [comment]
Thanks!

**Comment by SnappyDragon64** [comment]
Fixed, the file on curseforge has been swapped with a new version.
